
DROP DATABASE IF EXISTS 1702B;
CREATE DATABASE 1702B;

DROP TABLE IF EXISTS 1702B.account;
CREATE TABLE 1702B.account(
  userid INT AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT 'ID PK',
  account CHAR(12) NOT NULL COMMENT '帐号',
  password VARCHAR(40) NOT NULL COMMENT '密码'
);

DROP TABLE IF EXISTS 1702B.information;
CREATE TABLE 1702B.information(
  id INT PRIMARY KEY NOT NULL COMMENT 'ID PK',
  name CHAR(12) NOT NULL COMMENT '名字',
  phonenumber CHAR(11) NOT NULL COMMENT '手机号',
  email VARCHAR(30) NOT NULL COMMENT '邮箱',
  accountid INT COMMENT 'fk'

);

DROP TABLE IF EXISTS 1702B.hobby;
CREATE TABLE 1702B.hobby(
  id INT PRIMARY KEY NOT NULL COMMENT 'ID PK',
  hobbyname VARCHAR(255) NOT NULL COMMENT '爱好有哪些',
  accountid INT COMMENT 'fk'
);

SELECT *
FROM `1702B`.account;

SELECT *
FROM `1702B`.information;